# Generated by Django 4.1.9 on 2023-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('idprojeto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('areagestora', models.CharField(blank=True, db_column='AreaGestora', max_length=200, null=True)),
                ('projeto', models.CharField(blank=True, db_column='Projeto', max_length=200, null=True)),
                ('alinhamentoestrategico', models.CharField(blank=True, db_column='AlinhamentoEstrategico', max_length=200, null=True)),
                ('publicoalvo', models.CharField(blank=True, db_column='PublicoAlvo', max_length=200, null=True)),
                ('justificativa', models.CharField(blank=True, db_column='Justificativa', max_length=200, null=True)),
                ('stajeholder', models.CharField(blank=True, db_column='Stajeholder', max_length=200, null=True)),
                ('objetivo', models.CharField(blank=True, db_column='Objetivo', max_length=200, null=True)),
                ('prazo', models.DateField(blank=True, db_column='Prazo', null=True)),
                ('custo', models.DecimalField(blank=True, db_column='Custo', decimal_places=4, max_digits=10, null=True)),
                ('restricoes', models.CharField(blank=True, db_column='Restricoes', max_length=200, null=True)),
                ('requisitos', models.CharField(blank=True, db_column='Requisitos', max_length=200, null=True)),
                ('principaisriscos', models.CharField(blank=True, db_column='PrincipaisRiscos', max_length=200, null=True)),
                ('entregaveis', models.CharField(blank=True, db_column='Entregaveis', max_length=200, null=True)),
                ('beneficios', models.CharField(blank=True, db_column='Beneficios', max_length=200, null=True)),
                ('rebulamentacao', models.CharField(blank=True, db_column='Rebulamentacao', max_length=200, null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuariocriacao', models.BigIntegerField()),
                ('idusuarioalteracao', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoBecIndicador',
            fields=[
                ('idgbecindicador', models.CharField(db_column='idGBECIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('qtddownloadandroid', models.BigIntegerField(blank=True, db_column='QtdDownloadAndroid', null=True)),
                ('qtddownloaios', models.BigIntegerField(blank=True, db_column='QtdDownloaIOS', null=True)),
                ('acessossemanal', models.BigIntegerField(blank=True, db_column='AcessosSemanal', null=True)),
                ('servidoresdistintos', models.BigIntegerField(blank=True, db_column='ServidoresDistintos', null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_BEC_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoBpmIndicador',
            fields=[
                ('idbpmindicador', models.CharField(db_column='idBPMIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('economiacustoservico', models.DecimalField(blank=True, db_column='EconomiaCustoServico', decimal_places=4, max_digits=16, null=True)),
                ('tempoexecucaoservico', models.DecimalField(blank=True, db_column='TempoExecucaoServico', decimal_places=4, max_digits=16, null=True)),
                ('comparacaohumanosxdigital', models.DecimalField(blank=True, db_column='ComparacaoHumanosXDigital', decimal_places=4, max_digits=16, null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_BPM_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoCoeticIndicador',
            fields=[
                ('idcoeticindicador', models.CharField(db_column='idCOETICIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('demandanormaisvalor', models.DecimalField(blank=True, db_column='DemandaNormaisValor', decimal_places=4, max_digits=16, null=True)),
                ('demandanormaisqtd', models.BigIntegerField(blank=True, db_column='DemandaNormaisQtd', null=True)),
                ('demandaadnormaisvalor', models.DecimalField(blank=True, db_column='DemandaAdNormaisValor', decimal_places=4, max_digits=16, null=True)),
                ('demandaadnormaisqtd', models.BigIntegerField(blank=True, db_column='DemandaAdNormaisQtd', null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_COETIC_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoDatacenterIndicador',
            fields=[
                ('iddatacenterindicador', models.CharField(db_column='idDataCenterIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('certificacaotier3', models.DecimalField(blank=True, db_column='CertificacaoTier3', decimal_places=4, max_digits=16, null=True)),
                ('disasterrecovery', models.DecimalField(blank=True, db_column='DisasterRecovery', decimal_places=4, max_digits=16, null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_DataCenter_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoDoIndicador',
            fields=[
                ('iddondicador', models.CharField(db_column='idDOndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('mediapesquisadiaria', models.DecimalField(blank=True, db_column='MediaPesquisaDiaria', decimal_places=4, max_digits=16, null=True)),
                ('consultausuario', models.DecimalField(blank=True, db_column='ConsultaUsuario', decimal_places=4, max_digits=16, null=True)),
                ('consultaedicaodia', models.DecimalField(blank=True, db_column='ConsultaEdicaoDia', decimal_places=4, max_digits=16, null=True)),
                ('tempomediopermanenciasite', models.DecimalField(blank=True, db_column='TempoMedioPermanenciaSite', decimal_places=4, max_digits=16, null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_DO_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoGovbrIndicador',
            fields=[
                ('idgovbrindicador', models.CharField(db_column='idGOVBRIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('migracaosistema', models.IntegerField(blank=True, db_column='MigracaoSistema', null=True)),
                ('implementacaoecosistemaidp', models.IntegerField(blank=True, db_column='ImplementacaoEcosistemaIDP', null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_GOVBR_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetoindicador',
            fields=[
                ('idprojeto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idprojetoindicador', models.CharField(db_column='idprojetoIndicador', max_length=36)),
                ('formulacalculo', models.CharField(blank=True, db_column='FormulaCalculo', max_length=200, null=True)),
                ('idprojetotipounidade', models.IntegerField(blank=True, db_column='idprojetoTipoUnidade', null=True)),
                ('idprojetotipoperiodicidade', models.IntegerField(blank=True, db_column='idprojetoTipoPeriodicidade', null=True)),
                ('duracaoreporte', models.IntegerField(blank=True, db_column='DuracaoReporte', null=True)),
                ('alinhamentoestrategico', models.CharField(blank=True, db_column='AlinhamentoEstrategico', max_length=200, null=True)),
                ('publicoalvo', models.CharField(blank=True, db_column='PublicoAlvo', max_length=200, null=True)),
                ('justificativa', models.CharField(blank=True, db_column='Justificativa', max_length=200, null=True)),
                ('stajeholder', models.CharField(blank=True, db_column='Stajeholder', max_length=200, null=True)),
                ('objetivo', models.CharField(blank=True, db_column='Objetivo', max_length=200, null=True)),
                ('prazo', models.DateField(blank=True, db_column='Prazo', null=True)),
                ('custo', models.DecimalField(blank=True, db_column='Custo', decimal_places=4, max_digits=10, null=True)),
                ('restricoes', models.CharField(blank=True, db_column='Restricoes', max_length=200, null=True)),
                ('requisitos', models.CharField(blank=True, db_column='Requisitos', max_length=200, null=True)),
                ('principaisriscos', models.CharField(blank=True, db_column='PrincipaisRiscos', max_length=200, null=True)),
                ('entregaveis', models.CharField(blank=True, db_column='Entregaveis', max_length=200, null=True)),
                ('beneficios', models.CharField(blank=True, db_column='Beneficios', max_length=200, null=True)),
                ('rebulamentacao', models.CharField(blank=True, db_column='Rebulamentacao', max_length=200, null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuariocriacao', models.BigIntegerField()),
                ('idusuarioalteracao', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ProjetoIndicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoPortalspIndicador',
            fields=[
                ('idportalspindicador', models.CharField(db_column='idPortalSPIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('taxacrescimentousuario', models.DecimalField(blank=True, db_column='TaxaCrescimentoUsuario', decimal_places=4, max_digits=16, null=True)),
                ('notavaliacaolojaapp', models.BigIntegerField(blank=True, db_column='NotaValiacaoLojaApp', null=True)),
                ('roi', models.DecimalField(blank=True, db_column='ROI', decimal_places=4, max_digits=16, null=True)),
                ('taxaretencao', models.DecimalField(blank=True, db_column='TaxaRetencao', decimal_places=4, max_digits=16, null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_PortalSP_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoSeducIndicador',
            fields=[
                ('idseducindicador', models.CharField(db_column='idSeducIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('numeroprovas', models.BigIntegerField(blank=True, db_column='NumeroProvas', null=True)),
                ('numeroalunos', models.BigIntegerField(blank=True, db_column='NumeroAlunos', null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_Seduc_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoSegurancainfIndicador',
            fields=[
                ('idgsegurancainfindicador', models.CharField(db_column='idGSegurancaInfIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('ataquesbloqueadosfirewall', models.BigIntegerField(blank=True, db_column='AtaquesBloqueadosFirewall', null=True)),
                ('ataquesbloqueadosips', models.BigIntegerField(blank=True, db_column='AtaquesBloqueadosIPS', null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_SegurancaInf_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoSeiIndicador',
            fields=[
                ('idseiindicador', models.CharField(db_column='idSEIIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('documentosgerados', models.IntegerField(blank=True, db_column='DocumentosGerados', null=True)),
                ('processoscriados', models.IntegerField(blank=True, db_column='ProcessosCriados', null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_SEI_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoSneIndicador',
            fields=[
                ('idsneindicador', models.CharField(db_column='idSneIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('descontosolicitado', models.DecimalField(blank=True, db_column='DescontoSolicitado', decimal_places=4, max_digits=16, null=True)),
                ('multaspagas', models.DecimalField(blank=True, db_column='MultasPagas', decimal_places=4, max_digits=16, null=True)),
                ('valoreconomizado', models.DecimalField(blank=True, db_column='ValorEconomizado', decimal_places=4, max_digits=16, null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_SNE_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoSouIndicador',
            fields=[
                ('idgsouindicador', models.CharField(db_column='idGSOUIndicador', max_length=36, primary_key=True, serialize=False)),
                ('idprojeto', models.BigIntegerField()),
                ('qtddownloadandroid', models.BigIntegerField(blank=True, db_column='QtdDownloadAndroid', null=True)),
                ('qtddownloaios', models.BigIntegerField(blank=True, db_column='QtdDownloaIOS', null=True)),
                ('acessossemanal', models.BigIntegerField(blank=True, db_column='AcessosSemanal', null=True)),
                ('servidoresdistintos', models.BigIntegerField(blank=True, db_column='ServidoresDistintos', null=True)),
                ('boativo', models.BooleanField(blank=True, db_column='boAtivo', null=True)),
                ('datainclusao', models.DateTimeField()),
                ('dataalteracao', models.DateTimeField()),
                ('idusuarioa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Projeto_SOU_Indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetotipoperiodicidade',
            fields=[
                ('idprojetotipoperiodicidade', models.IntegerField(db_column='idprojetoTipoPeriodicidade', primary_key=True, serialize=False)),
                ('tipoperiodicidade', models.CharField(blank=True, db_column='TipoPeriodicidade', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ProjetoTipoPeriodicidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetotipounidade',
            fields=[
                ('idprojetotipounidade', models.IntegerField(db_column='idprojetoTipoUnidade', primary_key=True, serialize=False)),
                ('tipounidademedida', models.CharField(blank=True, db_column='TipoUnidadeMedida', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ProjetoTipoUnidade',
                'managed': False,
            },
        ),
    ]
